# Generated by Django 5.2.7 on 2026-02-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ls1', '0002_superuser_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='superuser',
            name='role',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('agent', 'Agent')], default='buyer', max_length=10),
        ),
    ]
